name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show repo files (debug)
        run: ls -la || true

      - name: Unzip uploaded ZIP if present
        run: |
          ZIP_NAME="mobile_fault_detector_full_package.zip"
          if [ -f "$ZIP_NAME" ]; then
            unzip -o "$ZIP_NAME" -d extracted
            ls -la extracted || true
          else
            echo "No ZIP named $ZIP_NAME found; proceeding with repo files."
            ls -la || true
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: '33.0.2'

      - name: Install Gradle (optional) so we can run 'gradle' if no gradlew
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.4'

      - name: Build debug APK (try wrapper if exists, otherwise use gradle)
        run: |
          set -e
          if [ -d "extracted/android" ]; then
            cd extracted/android
          elif [ -d "android" ]; then
            cd android
          fi

          if [ -f "./gradlew" ]; then
            chmod +x ./gradlew || true
            ./gradlew assembleDebug
          else
            if [ -f "build.gradle" ] || [ -d "app" ]; then
              gradle assembleDebug || ./gradlew assembleDebug || true
            else
              echo "No Android project found in this repo (no build.gradle or app/)."
              exit 1
            fi
          fi

      - name: Find
